apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gpu-cluster
  region: ap-northeast-1 

managedNodeGroups:
  - name: ng-gpu
    instanceType: p3.8xlarge
    minSize: 1
    maxSize: 4
    desiredCapacity: 2
    privateNetworking: true
    labels:
      lifecycle: gpu
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      allow: true
      publicKeyName: ap-northeast-11
